- hosts: nodes
  become: yes
  tasks:


  - name: install primary RabbitMQ signing key
    apt_key:
      url: "https://github.com/rabbitmq/signing-keys/releases/download/2.0/rabbitmq-release-signing-key.asc"
      state: present

  - name: Team RabbitMQ's main signing key
    apt_key:
      id: "F77F1EDA57EBB1CC"
      keyserver: "hkp://keyserver.ubuntu.com:80"
      state: present

  - name: install curl gnupg debian-keyring debian-archive-keyring apt-transport-https
    apt:
      pkg:
      - curl
      - gnupg
      - debian-keyring
      - debian-archive-keyring
      - apt-transport-https
      update_cache: yes




#  - name: Team RabbitMQ's main signing key
#    apt_key:
#      id: "0x0A9AF2115F4687BD29803A206B73A36E6026DFCA"
##      keyserver: "hkps://keys.openpgp.org"
##      state: present
#
#
  - name: Launchpad PPA that provides modern Erlang releases
    apt_key:
      id: "F77F1EDA57EBB1CC"
      keyserver: "keyserver.ubuntu.com"
      state: present
#
#  - name: add Erlang apt-key
#    apt_key:
#      url: https://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc
#      state: present
#
#  - name: Create a list file for Erlang
#    lineinfile:
#      path: /etc/apt/sources.list.d/erlang-solution.list
#      line: "deb https://packages.erlang-solutions.com/ubuntu focal contrib"
#      create: yes


  - name: add PackageCloud RabbitMQ repository apt-key
    apt_key:
      url: "https://packagecloud.io/rabbitmq/rabbitmq-server/gpgkey"
      state: present

  - name: Copy file with owner and permissions
    ansible.builtin.copy:
      src: rabbitmq.list
      dest: /etc/apt/sources.list.d/rabbitmq.list
      mode: '0644'



  - name: Add Launchpad PPA repository that provides Erlang packages produced by the RabbitMQ team
    blockinfile:
      path: /etc/apt/sources.list.d/erlang-solution.list
      block: |
        deb http://ppa.launchpad.net/rabbitmq/rabbitmq-erlang/ubuntu focal main
        deb-src http://ppa.launchpad.net/rabbitmq/rabbitmq-erlang/ubuntu focal main
      create: yes

  - name: install Erlang packages
    apt:
      pkg:
      - erlang-base
      - erlang-asn1
      - erlang-crypto
      - erlang-eldap
      - erlang-ftp
      - erlang-inets
      - erlang-mnesia
      - erlang-os-mon
      - erlang-parsetools
      - erlang-public-key
      - erlang-runtime-tools
      - erlang-snmp
      - erlang-ssl
      - erlang-syntax-tools
      - erlang-tftp
      - erlang-tools
      - erlang-xmerl
      update_cache: yes

  - name: Install rabbitmq-server and its dependencies
    apt:
      pkg:
      - rabbitmq-server
      update_cache: yes
